### ISSUE TITLE
FFI::addr() cannot create a reference to a temporary pointer

### ISSUE THREAD

**Issue by victorratts13** [CodeWithKyrian/transformers-php#28]
### Your question

I'm working on a personal project where I'm trying to load a simple model for testing. I'm having some problems with FFI where I get the error:

```php
FFI::addr() cannot create a reference to a temporary pointer
```

Enviroment:

- PHP 8.3
- Laravel 11
- MacOs 13.6.6 (22G630)

**Comment by CodeWithKyrian** [comment]
Can you provide more information about the model, and some code on how you set things up so I can try to reproduce the error?

**Comment by victorratts13** [comment]
UPDATE:

When I was debugging the code I came across this PHP alert

```php
 PHP Warning:  PHP Startup: Unable to load dynamic library 'ffi' (tried: /usr/local/lib/php/pecl/20230831/ffi (dlopen(/usr/local/lib/php/pecl/20230831/ffi, 0x0009): tried: '/usr/local/lib/php/pecl/20230831/ffi' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/php/pecl/20230831/ffi' (no such file), '/usr/local/lib/php/pecl/20230831/ffi' (no such file)), /usr/local/lib/php/pecl/20230831/ffi.so (dlopen(/usr/local/lib/php/pecl/20230831/ffi.so, 0x0009): tried: '/usr/local/lib/php/pecl/20230831/ffi.so' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/usr/local/lib/php/pecl/20230831/ffi.so' (no such file), '/usr/local/lib/php/pecl/20230831/ffi.so' (no such file))) in Unknown on line 0
```

I imagined it was something with the FFI library, so I decided to install it using perl, however, the message appears to me:

![Captura de Tela 2024-04-30 às 03 09 43](https://github.com/CodeWithKyrian/transformers-php/assets/19245467/5536ab0d-d5e7-4dee-a393-c4762790da62)

**Comment by CodeWithKyrian** [comment]
Hello @victorratts13. Does the problem still persist? It appears to be a problem with your FFI setup. If I may ask, how did you php? Herd, Brew or apt-get?

**Comment by victorratts13** [comment]
## I just found the problem.

1 - I installed an ubuntu-server VM to test outside my work environment.

2 - I installed all the development packages that transformersphp uses

```sh
sudo apt update && sudo apt install -y libffi-dev libz-dev libpng-dev git libzip-dev
```

3 - I ran the code again and it worked

## Conclusion

It remained to install the dependencies that make FFI work within the command line

**Comment by CodeWithKyrian** [comment]
Oh, that's great. I was going to suggest installing php-ffi using apt-get actually. I'm glad it's all resolved
