### ISSUE TITLE
Is size_divisibility supported?

### ISSUE THREAD

**Issue by k99k5** [CodeWithKyrian/transformers-php#52]
### System Info

PHP 8.3

### PHP Version

8.3

### Environment/Platform

- [X] Command-line application
- [ ] Web application
- [ ] Serverless
- [ ] Other (please specify)

### Description

PHP Fatal error:  Uncaught Error: Call to undefined method Codewithkyrian\Transformers\FeatureExtractors\ImageFeatureExtractor::enforceSizeDivisibility()

In ImageFeatureExtractor.php:309

### Reproduction

-

**Comment by CodeWithKyrian** [comment]
Fixed in v0.4.3
