### ISSUE TITLE
Setting default ImageProvider for Image to Text pipeline

### ISSUE THREAD

**Issue by roberto-butti** [CodeWithKyrian/transformers-php#63]
### System Info

Macos, PHP 8.3.10 (cli), 
codewithkyrian/transformers            0.5.1

### PHP Version

PHP 8.3.10 (cli)

### Environment/Platform

- [X] Command-line application
- [ ] Web application
- [ ] Serverless
- [ ] Other (please specify)

### Description

Using the pipeline image-to-text, and not using the `setImageDriver()` with `Transformers::setup()`, i receive this error: 
```
Fatal error: Uncaught RuntimeException: Image driver not set. Please set the image driver using `Transformers::setup()->setImageDriver()`
```
Looks like the default (according to the documentation) is not set.
If I set the image driver:
```
Transformers::setup()
->setImageDriver(ImageDriver::IMAGICK)->setCacheDir("./models")->apply();
```
It works.

### Reproduction

```
Transformers::setup()->setCacheDir("./models")->apply();

$pipeline = pipeline("image-to-text");

$result = $pipeline(
    "test-image.webp"
);
```

**Comment by CodeWithKyrian** [comment]
Oh, in previous versions of TransformersPHP, a default image driver was included by default, but that’s no longer the case in the latest update. Thanks for bringing this to my attention—I’ll be updating the documentation to reflect this change as soon as possible.
