### ISSUE TITLE
Unable to load shared object file

### ISSUE THREAD

**Issue by Awais-cb** [CodeWithKyrian/transformers-php#8]
### System Info

Linux ubuntu 20.04

### PHP Version

8.3

### Environment/Platform

- [X] Command-line application
- [x] Web application
- [ ] Serverless
- [ ] Other (please specify)

### Description

```
Type:        FFI\Exception
Message:     Failed loading '/var/www/html/od-web/vendor/ankane/onnxruntime/src/../lib/onnxruntime-linux-x64-1.17.0/lib/libonnxruntime.so.1.17.0' (/var/www/html/od-web/vendor/ankane/onnxruntime/src/../lib/onnxruntime-linux-x64-1.17.0/lib/libonnxruntime.so.1.17.0: cannot open shared object file: No such file or directory)
Filename:    /var/www/html/od-web/vendor/ankane/onnxruntime/src/FFI.php
Line Number: 16
```

### Reproduction

- Tried to installed the library using
`composer require codewithkyrian/transformers`
- Ran this command as well
`./vendor/bin/transformers install`

but later when i tried to use this code i got the exception mentioned above

**Comment by Awais-cb** [comment]
Sorry i didn't setup the cache path thanks for this exciting package

**Comment by CodeWithKyrian** [comment]
Oh that's cool. You're welcome
